"""Pack lookup, sharing, and export rendering."""

import json
from pathlib import Path

from . import db, security


def get_for_org(pack_id: int, org_id: int):
    return db.one("""SELECT cp.*, cr.name AS recipe_name, cr.slug AS recipe_slug, o.slug AS org_slug,
                            o.name AS org_name, o.company, o.audience
                     FROM content_packs cp
                     JOIN content_recipes cr ON cr.id=cp.recipe_id
                     JOIN organizations o ON o.id=cp.org_id
                     WHERE cp.id=? AND cp.org_id=?""", (pack_id, org_id))


def get_by_token(token: str):
    return db.one("""SELECT cp.*, cr.name AS recipe_name, cr.slug AS recipe_slug, o.slug AS org_slug,
                            o.name AS org_name, o.company, o.audience
                     FROM content_packs cp
                     JOIN content_recipes cr ON cr.id=cp.recipe_id
                     JOIN organizations o ON o.id=cp.org_id
                     WHERE cp.share_token=?""", (token,))


def body(pack) -> dict:
    return json.loads(pack["body_json"])


def ensure_share_token(pack_id: int) -> str:
    row = db.one("SELECT share_token FROM content_packs WHERE id=?", (pack_id,))
    if row and row["share_token"]:
        return row["share_token"]
    token = security.new_token(28)
    while db.one("SELECT id FROM content_packs WHERE share_token=?", (token,)):
        token = security.new_token(28)
    db.run("UPDATE content_packs SET share_token=?, updated_at=datetime('now') WHERE id=?",
           (token, pack_id))
    return token


def markdown(pack) -> str:
    data = body(pack)
    lines = [
        f"# {pack['title']}",
        "",
        f"Recipe: {pack['recipe_name']}",
        f"Workspace: {pack['company'] or pack['org_name']}",
        f"Status: {pack['status']}",
        "",
        "## Strategy",
        data.get("strategy", ""),
        "",
        "## Shot List",
    ]
    for item in data.get("shot_list", []):
        lines.append(f"- {item}")
    lines += ["", "## Captions"]
    for item in data.get("captions", []):
        lines.append(f"- {item}")
    lines += ["", "## Export Checklist"]
    for item in data.get("exports", []):
        lines.append(f"- {item}")
    lines += ["", "## Upsells"]
    for item in data.get("upsells", []):
        lines.append(f"- {item}")
    lines += ["", "_Generated by Platekit._", ""]
    return "\n".join(lines)


def plain_text(pack) -> str:
    return markdown(pack).replace("# ", "").replace("## ", "").replace("- ", "• ")


def filename(pack, ext: str) -> str:
    stem = "".join(c if c.isalnum() else "-" for c in pack["title"].lower()).strip("-")
    return f"{stem or 'platekit-pack'}.{ext}"
