"""Pack lookup and export rendering for the Mise read APIs."""

import json

from . import db


def get_for_org(pack_id: int, org_id: int):
    return db.one("""SELECT cp.*, cr.name AS recipe_name, cr.slug AS recipe_slug, o.slug AS org_slug,
                            o.name AS org_name, o.company, o.audience
                     FROM content_packs cp
                     JOIN content_recipes cr ON cr.id=cp.recipe_id
                     JOIN organizations o ON o.id=cp.org_id
                     WHERE cp.id=? AND cp.org_id=?""", (pack_id, org_id))


def body(pack) -> dict:
    return json.loads(pack["body_json"])


def markdown(pack) -> str:
    data = body(pack)
    lines = [
        f"# {pack['title']}",
        "",
        f"Recipe: {pack['recipe_name']}",
        f"Workspace: {pack['company'] or pack['org_name']}",
        f"Status: {pack['status']}",
        "",
        "## Strategy",
        data.get("strategy", ""),
        "",
        "## Shot List",
    ]
    for item in data.get("shot_list", []):
        lines.append(f"- {item}")
    lines += ["", "## Captions"]
    for item in data.get("captions", []):
        lines.append(f"- {item}")
    lines += ["", "## Export Checklist"]
    for item in data.get("exports", []):
        lines.append(f"- {item}")
    lines += ["", "## Upsells"]
    for item in data.get("upsells", []):
        lines.append(f"- {item}")
    lines += ["", "_Generated by Dionysus._", ""]
    return "\n".join(lines)
